Repository rockingrohit9639/project-zone, pull requests merged in 2021-07, with the labels that each got.

#167 Alignment
  package-lock.json
  package.json
Labels: LGMSOC21, 🟩 Level1

#179 Addproject by authenticated user frontend connected to backend
  server/controllers/user.js
  server/package-lock.json
  server/routes/ProtectedRoutes.js
  server/routes/projectRoutes.js
  src/axios/instance.js
  src/components/AddNewProject/AddNewProject.js
  src/components/Profile/Profile.js
Labels: LGMSOC21, 🟥 Level4

#182 store user messages to db and send relevant emails
  server/controllers/user.js
  server/db/schema/User.js
  server/routes/ProtectedRoutes.js
  src/axios/instance.js
  src/components/AddNewProject/AddNewProject.js
  src/components/ContactUs/contactus.js
  src/components/Navbar/Navbar.js
Labels: LGMSOC21, 🟥 Level4

#188 ADDED - SwaggerUI for server
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/ProtectedRoutes.js
  server/routes/authRoutes.js
  server/routes/projectRoutes.js
Labels: LGMSOC21, 🟧 Level3

#191 Added horizontal scrollbar on explore categories section
  package-lock.json
  src/components/Home/Home.css
  src/components/ProjectCategories/ProjectCategories.css
Labels: LGMSOC21, 🟩 Level1

#195 ADDED - 404 Not Found Page
  src/App.js
  src/components/PageNotFound/PageNotFound.css
  src/components/PageNotFound/PageNotFound.js
Labels: LGMSOC21, 🟧 Level3

#193 Added google login backend route and integrated it with frontend
  server/controllers/auth.js
  server/controllers/user.js
  server/db/schema/User.js
  server/routes/authRoutes.js
  server/routes/projectRoutes.js
  src/axios/instance.js
  src/components/Callback.js
Labels: LGMSOC21, 🟥 Level4

#197 Home Page Made Dynamic
  server/controllers/public.js
  server/routes/projectRoutes.js
  src/App.js
  src/axios/instance.js
  src/components/Home/Home.js
  src/components/Project/Project.js
  src/reducer.js
Labels: LGMSOC21, 🟧 Level3

#199 Added default options to search/show projects
  server/package-lock.json
  src/components/Project/Project.js
  src/components/ShowProjects/ShowProjects.css
  src/components/ShowProjects/Showprojects.js
  src/utils.js
Labels: LGMSOC21, 🟨 Level2

#203 addNew protected
  src/components/AddNewProject/AddNewProject.js
Labels: LGMSOC21, 🟩 Level1

#204 ADDED - Commenting Feature Implemented
  package-lock.json
  package.json
  server/controllers/user.js
  server/db/schema/projectSchema.js
  server/routes/ProtectedRoutes.js
  src/axios/instance.js
  src/components/Home/Home.js
  src/components/Project/Project.js
  src/components/ProjectDetails/ProjectDeatils.css
  src/components/ProjectDetails/ProjectDetails.js
  src/reducer.js
Labels: LGMSOC21, 🟥 Level4

#206 ProjectDetail Page Made Dynamic
  server/controllers/public.js
  server/routes/projectRoutes.js
  src/App.js
  src/axios/instance.js
  src/components/Project/Project.js
  src/components/ProjectDetails/ProjectDetails.js
Labels: LGMSOC21, 🟥 Level4

#207 Like increment feature with saving no of likes in database
  server/controllers/user.js
  server/routes/ProtectedRoutes.js
  src/axios/instance.js
  src/components/Home/Home.js
  src/components/Project/Project.css
  src/components/Project/Project.js
  src/components/ProjectDetailCard/ProjectDetailCard.css
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/reducer.js
Labels: LGMSOC21, 🟧 Level3

#211 Made all auth pages responsive
  src/components/ForgetPassword/Forget.css
  src/components/ForgetPassword/Forget.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/SetPasswordPage/SetPassword.css
  src/components/SignUp/SignUp.css
  src/components/SignUp/SignUp.js
  src/components/VerifyEmailPage/VerifyEmailPage.css
Labels: LGMSOC21, 🟨 Level2

#215 Shareable Feature Editted
  src/components/Project/Project.js
  src/components/ShareProject/ShareProject.js
Labels: LGMSOC21, 🟧 Level3

#218 Added Pagination on ShowProjects
  src/components/ShowProjects/ShowProjects.css
  src/components/ShowProjects/Showprojects.js
Labels: LGMSOC21, 🟧 Level3

#220 ADDED - Filter feature to filter projects on basis of level
  src/components/SearchBox/SearchBox.css
  src/components/ShowProjects/ShowProjects.css
  src/components/ShowProjects/Showprojects.js
Labels: LGMSOC21, 🟧 Level3

#227 Email Enabled on adding new Project
  server/controllers/user.js
Labels: LGMSOC21, 🟧 Level3

#229 Updating user projectones on adding new project
  server/controllers/user.js
  server/db/schema/User.js
  src/App.js
  src/components/AddNewProject/AddNewProject.js
  src/components/Profile/Profile.js
  src/components/ShowProjects/Showprojects.js
  src/reducer.js
Labels: LGMSOC21, 🟨 Level2

#233 project can start my one command
  package.json
  server/package-lock.json
  server/package.json
Labels: LGMSOC21, 🟩 Level1

#234 Saving projects liked or rated by user and showing status
  server/controllers/user.js
  server/db/schema/User.js
  src/App.js
  src/components/Project/Project.js
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/reducer.js
Labels: LGMSOC21, 🟧 Level3

#235 ADDED - New field to add github link on AddNewPoject Page
  package-lock.json
  server/controllers/user.js
  server/db/schema/projectSchema.js
  src/components/AddNewProject/AddNewProject.js
  src/components/Project/Project.css
  src/components/Project/Project.js
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/components/ProjectDetails/ProjectDetails.js
  src/reducer.js
Labels: LGMSOC21, 🟧 Level3

#239 Replaced previous images with the new ones
  Project_Img/Demo1_ProjectZone.png
  Project_Img/Demo2_ProjectZone.png
  Project_Img/Demo3_ProjectZone.png
  Project_Img/Demo4_ProjectZone.png
  Project_Img/Demo6_ProjectZone.png
  Project_Img/Demo7_ProjectZone.png
  README.md
  package-lock.json
Labels: LGMSOC21, 🟪 Level0

#237 Added badge feature based on user activity
  server/controllers/user.js
  server/db/schema/User.js
  server/routes/ProtectedRoutes.js
  src/axios/instance.js
  src/components/AddNewProject/AddNewProject.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Project/Project.js
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/components/ShowProjects/Showprojects.js
  src/utils.js
Labels: LGMSOC21, 🟥 Level4

#241 fixed images
  Project_Img/Demo3_ProjectZone.png
  src/assets/profileavatar.jpg
Labels: LGMSOC21, 🟥 Level4

#246 Added congrats badge popup screen
  src/components/AddNewProject/AddNewProject.css
  src/components/AddNewProject/AddNewProject.js
  src/components/CongratsBadgeScreen/CongratsBadgeScreen.css
  src/components/CongratsBadgeScreen/CongratsBadgeScreen.js
  src/components/Profile/Profile.css
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/components/ProjectDetails/ProjectDetails.js
  src/components/TrendingProjects/TrendingProjects.css
  src/components/TrendingProjects/TrendingProjects.js
Labels: LGMSOC21, 🟧 Level3

#253 Made Profile page dynamic based on profileid
  server/controllers/public.js
  server/routes/authRoutes.js
  server/routes/projectRoutes.js
  src/App.js
  src/axios/instance.js
  src/components/Navbar/Navbar.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/ProjectDetails/ProjectDetails.js
  src/reducer.js
Labels: LGMSOC21, 🟥 Level4

#249 Bug Fixed
  package-lock.json
  src/components/ProjectDetailCard/ProjectDetailCard.js
  src/components/ShareProject/ShareProject.js
Labels: LGMSOC21, 🟩 Level1

#256 Added upvote feature for project comments
  server/controllers/user.js
  server/db/schema/User.js
  server/db/schema/projectSchema.js
  server/routes/ProtectedRoutes.js
  src/App.js
  src/axios/instance.js
  src/components/ProjectDetails/ProjectDeatils.css
  src/components/ProjectDetails/ProjectDetails.js
  src/reducer.js
Labels: LGMSOC21, 🟧 Level3

#261 Scroll to top on every route
  src/App.js
  src/components/ScrollComponent/ScrollToTop.js
Labels: LGMSOC21, 🟩 Level1

#263 Fixed profile rendering
  server/db/schema/User.js
  src/App.js
  src/components/Profile/Profile.js
Labels: LGMSOC21, 🟧 Level3

#264 Added id for projects added with project links on profile
  server/controllers/user.js
  server/db/schema/User.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
Labels: LGMSOC21, 🟧 Level3

#267 Search box focus on space
  src/components/SearchBox/SearchBox.js
Labels: LGMSOC21, 🟨 Level2

#279 update (leaderboard ) till 275
  LEADERBOARD.md
Labels: documentation
