Repository rockingrohit9639/project-zone, pull requests merged in 2021-06, with the labels that each got.

#65 Folder structure added
  server/config/.env
  server/config/db.js
  server/controllers/index.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/routes.js
Labels: LGMSOC21, 🟨 Level2

#81 Open Source Section Added #77
  README.md
Labels: LGMSOC21, 🟪 Level0

#88 Added logo in readme
  README.md
Labels: LGMSOC21, 🟪 Level0

#99 Added the icon in the footer
  .eslintcache
  package-lock.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/icon.png
Labels: LGMSOC21, 🟩 Level1

#100 trending-projects
  src/App.js
  src/components/Home/Home.js
  src/components/Navbar/Navbar.js
Labels: LGMSOC21, 🟨 Level2

#98 fix a bug after changing search query
  package.json
  src/client.js
  src/components/Home/Home.js
  src/components/Project/Project.js
  src/components/RatingCard/RatingCard.js
  src/components/SearchBox/SearchBox.js
  src/components/ShowProjects/Showprojects.js
  src/reducer.js
Labels: LGMSOC21, 🟨 Level2

#101 Updated README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#102 added project categories
  src/assets/android.svg
  src/assets/js.svg
  src/assets/python.svg
  src/assets/react.svg
  src/assets/web.svg
  src/components/Home/Home.js
  src/components/ProjectCategories/ProjectCategories.css
  src/components/ProjectCategories/ProjectCategories.js
Labels: LGMSOC21, 🟧 Level3

#103 Update README.md Preview Screenshots
  Project_Img/Demo1_ProjectZone.png
  Project_Img/Demo2.png
  Project_Img/Demo2_ProjectZone.png
  Project_Img/Demo3_ProjectZone.png
  Project_Img/Demo4_ProjectZone.png
  Project_Img/Demo5_ProjectZone.png
  Project_Img/Demo6_ProjectZone.png
  README.md
Labels: LGMSOC21, 🟪 Level0

#106 Redesign of Contact Us page
  src/components/ContactUs/Illustration.svg
  src/components/ContactUs/contactus.css
  src/components/ContactUs/contactus.js
Labels: LGMSOC21, 🟧 Level3

#110 Added Responsive Navbar
  src/App.css
  src/App.js
  src/components/Footer/Footer.css
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/Navbar/Navbar.js
Labels: LGMSOC21, 🟧 Level3

#113 adding icon and change style of login button in navbar
  package-lock.json
  package.json
  src/App.css
  src/components/Navbar/Navbar.js
Labels: LGMSOC21, 🟨 Level2

#118 User sent to Fresh New Page upon Contact Form Submission with success message displayed
  src/components/ContactUs/contactus.js
Labels: LGMSOC21, 🟩 Level1

#119 Add New Project, Dashboard for Authenticated user only
  src/App.css
  src/components/Home/Home.css
  src/components/Login/Login.js
  src/components/Navbar/Navbar.js
Labels: LGMSOC21, 🟨 Level2

#122 Added prettier command
  .prettierrc.js
  package.json
Labels: LGMSOC21, 🟩 Level1

#124 Changed project card design and home projects layout
  src/assets/cardtop.svg
  src/assets/share.svg
  src/components/Home/Home.css
  src/components/Home/Home.js
  src/components/Project/Project.css
  src/components/Project/Project.js
  src/components/ShareProject/ShareProject.css
Labels: LGMSOC21, 🟧 Level3

#127 Login & Signup integrated with backend
  server/controllers/auth.js
  server/middlewares/auth.js
  server/routes/authRoutes.js
  src/App.js
  src/axios/instance.js
  src/components/Login/Login.js
  src/components/Navbar/Navbar.js
  src/components/SignUp/SignUp.js
  src/reducer.js
  src/utils.js
Labels: LGMSOC21, 🟧 Level3

#136 Added - Protected Routes for fetching and updating user dashboard data
  server/controllers/auth.js
  server/controllers/index.js
  server/controllers/user.js
  server/db/schema/User.js
  server/routes/ProtectedRoutes.js
  server/routes/authRoutes.js
Labels: LGMSOC21, 🟥 Level4

#138 added-comment-section
  src/components/ProjectDetails/ProjectDeatils.css
  src/components/ProjectDetails/ProjectDetails.js
Labels: LGMSOC21, 🟨 Level2

#142 About page
  package-lock.json
  package.json
  src/App.js
  src/components/About/about.css
  src/components/About/about.js
  src/components/About/icon.png
Labels: LGMSOC21, 🟧 Level3

#147 Added steps to run server locally & Updated images in Readme.md
  Project_Img/Demo2_ProjectZone.png
  Project_Img/Demo3_ProjectZone.png
  Project_Img/Demo4_ProjectZone.png
  Project_Img/Demo5_ProjectZone.png
  Project_Img/Demo7_ProjectZone.png
  Project_Img/Server.png
  README.md
  package-lock.json
Labels: LGMSOC21, 🟩 Level1

#144 Updated Particle Background Animation
  package-lock.json
  package.json
  src/components/ContactUs/contactus.js
  src/components/ProjectDetails/ProjectDetails.js
  src/components/TrendingProjects/TrendingProjects.js
Labels: LGMSOC21, 🟩 Level1

#152 About Route Bug in Footer fixed successfully
  src/components/Footer/Footer.js
Labels: LGMSOC21, 🟪 Level0

#156 scroll to top button
  src/App.css
Labels: LGMSOC21, 🟩 Level1

#159 Added Editprofile modal with form-state-handling and validation
  src/components/ContactUs/contactus.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Project/Project.js
Labels: LGMSOC21, 🟧 Level3

#162 responsive about us
  src/components/About/about.css
  src/components/About/about.js
Labels: LGMSOC21, 🟨 Level2

#165 Profile page integrated with server
  package-lock.json
  package.json
  server/controllers/user.js
  server/db/schema/User.js
  server/routes/ProtectedRoutes.js
  src/App.js
  src/assets/user.png
  src/axios/instance.js
  src/components/Navbar/Navbar.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/reducer.js
Labels: LGMSOC21, 🟥 Level4

#171 Resigned Add New Project Page
  src/assets/addprojectimg.png
  src/components/AddNewProject/AddNewProject.css
  src/components/AddNewProject/AddNewProject.js
Labels: LGMSOC21, 🟧 Level3

#169 Search project by hitting enter
  src/components/SearchBox/SearchBox.js
Labels: LGMSOC21, 🟨 Level2

#173 Footer Hover Animation successfully imported
  src/components/Footer/Footer.css
Labels: LGMSOC21, 🟪 Level0
